In [41]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [51]:
iris = load_iris()

In [52]:
# iris

In [53]:
iris_data = iris.data

In [54]:
iris_label = iris.target
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [55]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [56]:
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [57]:
# list = [
#     (iris_df['label'] == 0) ,
#     (iris_df['label'] == 1) ,
#     (iris_df['label'] == 2)]
# choicelist = iris.target_names
# iris_df['label name'] = np.select(list, choicelist, default = 'Not Specific')

In [58]:
# iris_df.head()

In [60]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=11)

In [62]:
X_train[:10]

array([[5.1, 2.5, 3. , 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5]])

In [63]:
X_test[:10]

array([[6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.9, 4.7, 1.4]])

In [64]:
y_train[:10]

array([1, 1, 0, 2, 0, 2, 2, 1, 2, 1])

In [65]:
y_test[:10]

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1])

In [67]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [70]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [71]:
pred = dt_clf.predict(X_test)

In [72]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2])

In [74]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.9111111111111111