In [19]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd

item = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(item)
encoder.transform(item)

array([0, 1, 4, 5, 3, 3, 2, 2])

In [2]:
#인코딩 전 원래의 값 확인
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [3]:
#인코딩된 값 디코딩
encoder.inverse_transform([3,0,2,1])

array(['선풍기', 'TV', '믹서', '냉장고'], dtype='<U5')

# OneHotEncoder

In [12]:
#숫자값으로 변환을 위해 LabelEncoder로 변환
item = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(item)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [13]:
#2차원 데이터로 변환
labels = labels.reshape(-1,1)

In [16]:
one_encoder = OneHotEncoder()
one_encoder.fit(labels)
one_labels = one_encoder.transform(labels)

In [18]:
one_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

# pandas API 사용 원핫 인코딩 수행

In [21]:
df = pd.DataFrame(item)

In [24]:
pd.get_dummies(df)

0_TV  0_냉장고  0_믹서  0_선풍기  0_전자레인지  0_컴퓨터
0     1      0     0      0        0      0
1     0      1     0      0        0      0
2     0      0     0      0        1      0
3     0      0     0      0        0      1
4     0      0     0      1        0      0
5     0      0     0      1        0      0
6     0      0     1      0        0      0
7     0      0     1      0        0      0

In [25]:
#넘파이로 변환해서 출력
pd.get_dummies(df).to_numpy()

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

# 피쳐 스케일링과 정규화

In [28]:
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)

print(iris_df.mean(), '\n', iris_df.std())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64 
 sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


## StandardScaler

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
# print(iris_scaled[5])
iris_scaled_df = pd.DataFrame(iris_scaled, columns=iris.feature_names)

print(iris_scaled_df.mean())
print(iris_scaled_df.std())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64


## MinMaxScaler

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
# print(iris_scaled)
iris_scaled_df = pd.DataFrame(iris_scaled, columns=iris.feature_names)

print(iris_scaled_df.min())
print(iris_scaled_df.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
